private static final List<String> RECIPES = Arrays.asList(
        "Aloo Fry",
        "Aloo Gobi",
        "Aloo Tikki",
        "Andhra Chicken Fry",
        "Appam",
        "Authentic Kebab",
        "Avial",
        "Baati",
        "Bagara Rice",
        "Barfi",
        "Bendakaya Fry",
        "Bendakaya",
        "Bhakri",
        "Bhelpuri",
        "Bhujia",
        "Bihari Litti",
        "Biryani Dum Pukht",
        "Biryani Rice",
        "Biryani",
        "Bonda",
        "Bottle Gourd Fry",
        "Brinjal Fry",
        "Burdwan Chicken",
        "Burfi",
        "Butter Chicken",
        "Butter Naan",
        "Calcutta Biryani",
        "Cauliflower Masala",
        "Chakli",
        "Chana Masala",
        "Cheese Dosa",
        "Chicken 65",
        "Chicken Biryani",
        "Chicken Curry",
        "Chicken Tikka Masala",
        "Chikhalwali Chips",
        "Chikhalwali",
        "Chole Bhature",
        "Coconut Curry",
        "Coconut Rice",
        "Dal Makhani",
        "Dhokla",
        "Dosa",
        "Dum Biryani",
        "Dum Pukht Chicken",
        "Egg Biryani",
        "Filter Coffee",
        "Fir Ni",
        "Fish Biryani",
        "Fish Curry",
        "France Biryani",
        "Gajar Ka Halwa",
        "Galauti Kebab",
        "Garlic Naan",
        "Gongura Chicken",
        "Gongura",
        "Green Curry",
        "Gujhia",
        "Gulab Jamun",
        "Haleem",
        "Halwa",
        "Hyderabadi Biryani",
        "Hyderabadi Haleem",
        "Idli",
        "Inippu",
        "Jalebi",
        "Kachumber Salad",
        "Kadhi",
        "Kalakand",
        "Kashmir Pulao",
        "Kebab",
        "Kesari",
        "Kheer",
        "Khichdi",
        "Kulcha",
        "Lachcha Paratha",
        "Laddu",
        "Ladoo",
        "Lemon Rice",
        "Luchi",
        "Lucknowi Biryani",
        "Lucknowi Kebab",
        "Makai Roti",
        "Makki Ki Roti",
        "Malpua",
        "Masala Dosa",
        "Masala Peanuts",
        "Medhu Vada",
        "Medu Vada",
        "Memoni Biryani",
        "Milk Cake",
        "Mirchi Ka Salan",
        "Mohan Thal",
        "Munakada Biryani",
        "Murukku",
        "Mushroom Curry",
        "Mutter Paneer",
        "Mutton Biryani",
        "Mutton Curry",
        "Naan",
        "Natu Kodi",
        "Nawabi Keema",
        "Nihari",
        "Onion Bhajiya",
        "Pakora",
        "Palak Paneer",
        "Panasa Kaya Biryani",
        "Paneer Biryani",
        "Paneer Chakli",
        "Paneer Tikka Masala",
        "Paneer Tikka",
        "Pani Puri",
        "Paratha",
        "Paya",
        "Payesh",
        "Peda",
        "Pesarattu",
        "Petha",
        "Poha",
        "Pongal",
        "Poori",
        "Pulihora",
        "Puri",
        "Puttu",
        "Raita",
        "Rajma",
        "Rasam",
        "Rasgulla",
        "Rasmalai",
        "Rasogulla",
        "Red Curry",
        "Rogan Josh",
        "Roti",
        "Saag Roti",
        "Sambar",
        "Samosa Chat",
        "Samosa",
        "Sandesh",
        "Seekh Kebab",
        "Sev Tameta",
        "Shami Kabab",
        "Sheekh Kabab",
        "Shrimp Curry",
        "Spring Roll",
        "Tamarind Rice",
        "Tandoori Chicken",
        "Tandoori Paneer",
        "Tomato Based Gravy",
        "Tortilla",
        "Ulava Caru Biryani",
        "Unappakaya",
        "Upma",
        "Uttam Idli",
        "Uttapam",
        "Vada",
        "Vankai Biryani",
        "Vegetable Biryani"
);